[pytest]
# AttributeError in pytest with asyncio after include code in fixtures
asyncio_mode = auto

faulthandler_timeout=180
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    timeout: marks test timeout duration
    asyncio: marks that run async tests
    repeat: marks that test run n times